### ISSUE TITLE
Meteor Installation: "no such package"

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/UI-Accordion#1]
No package named Ui-accordion found via the console. I also note that this package is not on atmosphere either...

Thanks in advance for the update!

**Comment by mklueh** [comment]
Any news on this issue?

**Comment by jlukic** [comment]
Weird it should be autopublished, I'll look

**Comment by jlukic** [comment]
Fixed, autopublish hook wasn't on for accordion, ad, embed, and visibility. Not sure why.
https://atmospherejs.com/semantic/ui-accordion

**Comment by mklueh** [comment]
Wow, that was fast. Thank you very much;)
