### ISSUE TITLE
Docs: document className.animating, selector.trigger

### ISSUE THREAD

**Issue by timkelty** [Semantic-Org/UI-Accordion#2]
These aren't mentioned in the docs, but exist.

**Comment by jlukic** [comment]
Can you be more specific? I'm not sure I understand what you're talking about

**Comment by timkelty** [comment]
See here: http://semantic-ui.com/modules/accordion.html#module

`className.animating` and `selector.trigger` are relevant settings, but they are not listed on the documentation page.

**Comment by jlukic** [comment]
Ah ok, sorry. Didnt see which repo this issue was attached to.
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/b620ded9e718328fa87dd2a9ac3fc8d33fa99f28

You can add docs issues in future to that repo

**Comment by timkelty** [comment]
Ah, sorry I didn't see the docs repo.

**Comment by jlukic** [comment]
No worries!
